apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-annotations-cadv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-annotations-cadv
    app.kubernetes.io/part-of: build-suite-test-application-bfzs
  name: test-annotations-cadv
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-nginx
      app.kubernetes.io/instance: test-annotations-cadv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx
        app.kubernetes.io/instance: test-annotations-cadv
    spec:
      containers:
      - image: quay.io/tnevrlka-test/build-e2e-fsud-tenant/build-suite-test-application-bfzs/test-annotations-cadv@sha256:9d12da5b5f0b9d5454b8d14c0140f48ef166cce83d76080fa0edc29497ce44fb
        name: my-nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
